name: Dispatch Pull Repo

steps:
- uses: actions/github-script@v6
  with:
    github-token: ${{ secrets.GH_TOKEN }}
    script: |
      await github.rest.actions.createWorkflowDispatch({
       owner: '${{ vars.REPO_OWNER }}',
       repo: '${{ vars.REPO_NAME }}',
       workflow_id: 'pull-repos.yml',
       ref: 'main'
      })

